config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "", to: "blogs#index"
  get "/blog/new", to: "blogs#new"
  post "/blog/create", to: "blogs#create"
  get "/blog/index", to: "blogs#index", as: "blog_index"
  get "/blog/:id", to: "blogs#show", as: "blog_show"
  put "/blog/:id/update", to: "blogs#update", as: "blog_update"
  get "/blog/:id/edit", to: "blogs#edit", as: "blog_edit"
  delete "/blog/:id", to: "blogs#destroy", as: "blog_delete"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def new
        @blog = Blog.new
    end

    def index
        @blog = Blog.all.with_attached_image
    end

   #POST method for new user add
   def create
        @blog = Blog.new(blog_params)
        if @blog.save
            redirect_to blog_index_path
        else
            render plain: "No, New user found!"
        end
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def edit
        @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])

        if @blog.update(blog_params)
            redirect_to blog_show_path
        else
            render plain: "Updation failed!"
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        
        redirect_to blog_index_path
    end


    private

    def blog_params
        params.require(:blog).permit(:title, :article, :published_year, :rating, :author, :image)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.erb
<h1>Update your post</h1>

<%= form_with model: @blog, url: blog_update_path(@blog), method: :PUT do |form|%>
    <div class="mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :article%>
        <%= form.text_field :article, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :author%>
        <%= form.text_field :author, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :image%>
        <%= form.file_field :image, class: "form-control", placeholder: "User"%>
    </div>
    <div class="mb-3">
        <%= form.label :published_year%>
        <%= form.number_field :published_year, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :rating%>
        <%= form.number_field :rating, class: "form-control"%>
    </div>

    <div class="mb-3">
        <%= form.submit "ADD", class: "btn btn-primary"%>
    </div>
<%end%>

app/views/blogs/index.html.erb
<%= stylesheet_link_tag('blog_index')%>
<div class="nav">
  <h1>Blogs</h1>
  <h4><%= link_to "Write Your Blog", blog_new_path%></h4>
</div>
<div class="row">
  <% @blog.each do |blog|%>
    <div class="col-4">
      <div class="row">
        <% if blog.image.attached? %>
          <img src=<%=(url_for(blog.image))%>>
        <% end %>
      </div>
      <div class="text">
        <a class="row title" href="/blog/<%= blog.id %>">
          <h3><%= blog.title %></h3>
        </a>
        <div class="row">
          <p class="article"><%= blog.article %></p>
        </div>
        <div class="row">
          <p class="col-6"><%= blog.published_year %></p>
          <p class="col-6 rating"><%= blog.rating %></p>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/blogs/new.html.erb
<h1>Create Yuor Own Post</h1>

<%= form_with model: @blog, url: blog_create_path, multipart: true  do |form| %>
    <div class="mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: "form-control", placeholder: "Title"%>
    </div>
    <div class="mb-3">
        <%= form.label :article%>
        <%= form.text_field :article, class: "form-control", placeholder: "Write about...."%>
    </div>
    <div class="mb-3">
        <%= form.label :author%>
        <%= form.text_field :author, class: "form-control", placeholder: "User"%>
    </div>
    <div class="mb-3">
        <%= form.label :image%>
        <%= form.file_field :image, class: "form-control", placeholder: "User"%>
    </div>
    <div class="mb-3">
        <%= form.label :published_year%>
        <%= form.number_field :published_year, class: "form-control", placeholder: "Published Year"%>
    </div>
    <div class="mb-3">
        <%= form.label :rating%>
        <%= form.number_field :rating, class: "form-control", placeholder: "Scale Rate"%>
    </div>

    <div class="mb-3">
        <%= form.submit "ADD", class: "btn btn-primary"%>
    </div>
<%end%>

app/views/blogs/show.html.erb
<%= stylesheet_link_tag('blog_show')%>
<div class="nav">
  <h1>
    Article-<%= @blog.id%>
  </h1>
  <div >
    <%= link_to "Home", blog_index_path, class: "edit" %>
    <%= link_to "Edit", blog_edit_path, class: "edit" %>
    <%= link_to "  Delete", blog_delete_path(@blog), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: "edit"%>
  </div>
</div>

<div class="row">
  <div class="col-4">
    <div class="row">
       <% if @blog.image.attached? %>
          <img src=<%=(url_for(@blog.image.variant(resize_to_fit: [200, 200])))%>>
        <% end %>
    </div>
    <div class="text">
      <a class="row title" href="/blog/<%= @blog.id %>">
        <h3><%= @blog.title %></h3>
      </a>
      <div class="row">
        <p class=""><%= @blog.article %></p>
      </div>
      <div class="row">
        <p class="col-12">Author- <%= @blog.author %></p>
      </div>
      <div class="row">
        <p class="col-6"> <%=  @blog.published_year %></p>
        <p class="col-6 rating"><%= @blog.rating %></p>
      </div>
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newdemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/new.html.erb
<h1>Hello, You are on the main page..</h1>